# Generated by Django 4.0.4 on 2022-08-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile1.jpeg', upload_to='profile_images'),
        ),
    ]
